##################################################################################
# VARIABLES
##################################################################################

variable "private_key_path" {
  description = "Path to the private key used to SSH into the EC2 instance"
}

variable "key_name" {
  description = "Key Pair to be used to for the EC2 instance"
}

variable "common_name" {
  default     = ""
  description = "Name of a prefix used for all resources generated by these scripts"
}
